title: <p align="center"> Francisco Javier<br>Guillén Navarro </p>

logo: "/images/picture.png?raw=true"

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/fj-guillen-navarro/">LinkedIn</a> |
  <a href="https://github.com/fjguillen-96">GitHub</a>
  </p>
  
  <p align="justify">
  I am aerospace engineer at Polytechnic University of Madrid
  <br><br>
  Currently, I am working at Airbus on behalf of Aertec performing digitalization and automation tasks in the A330-MRTT manufacturing process.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
