# Personal information
title: Francisco Javier Guillén Navarro
subtitle: Aerospace Engineer
logo: "/images/logo.png?raw=true"
description: >
  An aerospace engineer with a passion for programming and artificial intelligence

# Contact information
contacts:
  - icon: fas fa-map-marker-alt
    title: Location
    value: C/Amado Nervo, Madrid
  - icon: fab fa-linkedin
    title: LinkedIn
    value: https://www.linkedin.com/in/fj-guillen-navarro/
  - icon: fab fa-github
    title: GitHub
    value: https://github.com/fjguillen-96