title: <p align="center"> Chris Tran </p>

logo: "/images/picture.png?raw=true"

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/chriskhanhtran/">LinkedIn</a> |
  <a href="https://github.com/chriskhanhtran">GitHub</a>
  </p>
  
  <p align="justify">
  I am MS degree in Aerospace Engineering at Polytechnic University of Madrid
  <br><br>
  Currently, I am working at Airbus on behalf of Aertec performing digitalization and automation tasks in the A330-MRTT manufacturing process.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
